version: "3.3"
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      # Putting vars here for convinience for prod use env_file
      MYSQL_DATABASE: "test"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - "3306:3306"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: golang-geo-app
    depends_on:
      - mysql
    environment:
      DB_URL: admin:admin@tcp(localhost:3306)/test
    ports:
      - "3001:3001"
    command: sh entry_point.sh
