version: "3.3"
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      # Putting vars here for convinience for prod use env_file
      MYSQL_DATABASE: "test"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: golang-geo-app
    depends_on:
      - mysql
    command: sh -c "/wait && ./app/go_server_app"
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
volumes:
  my-db:
