version: "3.3"
services:
  db:
    image: mysql
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: golang-geo-app
    depends_on:
      - db
    environment:
      DB_URL: root:admin@tcp(db_mysql:3306)/test
    ports:
      - "3001:3001"
    command: sh entry_point.sh
